version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=churchrota
      - DB_USER=rota_user
      - DB_PASSWORD=rota_password
      - DB_PREFIX=cr_
      - AUTH_SCHEME=database
      - EMAIL_METHOD=mailgun
      - APP_ENV=development
    depends_on:
      - db
    volumes:
      - ./logs:/var/www/html/logs

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: churchrota
      MYSQL_USER: rota_user
      MYSQL_PASSWORD: rota_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 