[build]
builder = "nixpacks"

[deploy]
startCommand = "bash scripts/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PHP_VERSION = "7.4" 