#!/bin/bash

# Railway Setup Script for Rota Management Software
# This script helps you set up the environment variables and database

echo "🚂 Railway Setup for Rota Management Software"
echo "=============================================="
echo ""

# Database connection details from Railway
DB_HOST="mysql.railway.internal"
DB_NAME="railway"
DB_USER="root"
DB_PASSWORD="cRyfgtFAITBVWVNPkYFksVZDMSBvsgBo"
DB_PREFIX="cr_"

echo "📋 Environment Variables to set in Railway Dashboard:"
echo "====================================================="
echo ""
echo "Go to your Railway dashboard and add these variables to your 'rota' service:"
echo ""
echo "DB_HOST=$DB_HOST"
echo "DB_NAME=$DB_NAME"
echo "DB_USER=$DB_USER"
echo "DB_PASSWORD=$DB_PASSWORD"
echo "DB_PREFIX=$DB_PREFIX"
echo "APP_ENV=production"
echo "AUTH_SCHEME=database"
echo "EMAIL_METHOD=mailgun"
echo ""
echo "📝 Steps to set up in Railway Dashboard:"
echo "1. Go to your Railway project dashboard"
echo "2. Click on the 'rota' service"
echo "3. Go to the 'Variables' tab"
echo "4. Add each variable above"
echo "5. Deploy the service"
echo ""
echo "🔗 Database Connection Details:"
echo "Host: $DB_HOST"
echo "Database: $DB_NAME"
echo "User: $DB_USER"
echo "Port: 3306"
echo ""
echo "🌐 After deployment, your app will be available at:"
echo "https://your-app-name.railway.app"
echo ""
echo "📖 Next Steps:"
echo "1. Set the environment variables in Railway dashboard"
echo "2. Deploy the application"
echo "3. Visit the application URL"
echo "4. Follow the installation wizard to set up the database tables"
echo "5. Create your first admin user"
echo ""
echo "✅ Setup complete! Follow the steps above to configure your application." 